### ISSUE TITLE
qtarget Targeting is glitching in and out inside instance

### ISSUE THREAD

**Issue by SumnDaiy** [QuantusRP/qtarget#1]
I put a BoxZone inside my property, and when I try to use targeting on it it flickers

**Comment by SumnDaiy** [comment]
https://streamable.com/xec4if
Heres a video of it happening.

**Comment by thelindat** [comment]
Can you confirm this only happens inside an interior, and isn't happening with boxzones in general?

**Comment by SumnDaiy** [comment]
I'm like 90% sure. All of my other box zones out of instance works for me.
Tried to ask other people to test it, got no response

**Comment by Smokiiee** [comment]
Can confirm it doing som crazy thing when you are in a instance

https://streamable.com/ay22iu
