### ISSUE TITLE
canInteract

### ISSUE THREAD

**Issue by Svetlinvass** [QuantusRP/qtarget#10]
When i have canInteract and return something different than false the eye gets stuck. I mean it won't show the eye again.. I made a lot of debugs and i still can't find the problem.. i think  that the newest version is kinda broken idk.. bc it brakes on the js when it send NUI message validTarget and in the data it have canInteract. And when i remove canInteract from the send_options array it stop 'crashing' the eye but for some reason it stops checking for the function in the checkOptions function

**Comment by thelindat** [comment]
If canInteract is getting sent to NUI then you have it setup wrong.

```lua
canInteract = function(entity)
    if GetEntityHealth(entity) ~= 0 then return true
    else return false end
end
```

Always return true or false.
