### ISSUE TITLE
Quick Question about ESX v1.2

### ISSUE THREAD

**Issue by BlueSky-fur** [QuantusRP/qtarget#3]
We currently use ESX v1.2 and there isnt a imports.lua

how should we proceed now? 

Create the file ourselves, or isnt it even needed then?

or does it perhaps also can go into the functions.lua?

**Comment by BerkieBb** [comment]
@BlueSky-fur 
This is QTarget, this is not the place to ask for support on es_extended

**Comment by BerkieBb** [comment]
Oh you don't have to search it up, it's already in the readme of qtarget under Dependencies

**Comment by thelindat** [comment]
You can put the function anywhere, the reason it's suggested to add it to imports is because most releases by myself or under QRP in the future will be utilising it.

ESX Legacy, or 1.3, is compatible with 1.2 resources (there's a very tiny list of incompatibilities due to spawnmanager being used).
