### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Ventraks** [QuantusRP/qtarget#8]
Hello, i got instantly this error
![Snímek obrazovky 2021-07-21 214302](https://user-images.githubusercontent.com/83806248/126550176-bc9dd5e7-9866-4395-a173-1eacb8a4e81e.png)

**Comment by AscendoTuum86** [comment]
Not sure why this was labeled as won't fix? I have the same issue. There is no pull request merged to show it was fixed.

**Comment by thelindat** [comment]
It was not a bug, it was an error caused by _not reading the instructions_.

It's not even valid at this point because I've removed the need for Intervals in the released version of the resource.
